/* Fise complete per substanta. Surse: fisa furnizorului MKM ("dozaj si administrare", aug 2026)
   si "Raport de analiza peptide" (19 aug 2026). Sinteza informativa, nu recomandare medicala. */
const INFO = {
  shb: {
    what: "Amestec de aminoacizi liberi pentru administrare parenterală, nu peptidă. Per flacon de 10 ml: L-arginină 110 mg, L-ornitină 110 mg, L-citrulină 120 mg, L-lizină 70 mg, L-glutamină 40 mg, L-prolină 60 mg, L-taurină 60 mg, L-carnitină 220 mg, N-acetilcisteină 75 mg. Total 865 mg, adică 86,5 mg/ml.",
    mechanism: ["Arginina și citrulina sunt precursori de oxid nitric; citrulina crește arginina plasmatică mai eficient decât arginina directă.", "Arginina, ornitina și lizina au fost studiate ca secretagoge de hormon de creștere.", "Carnitina transportă acizii grași cu lanț lung în mitocondrie pentru beta-oxidare.", "N-acetilcisteina este precursorul limitant pentru sinteza de glutation."],
    evidence: { level: "Doze subterapeutice", text: "Mecanismele sunt reale, dozele nu: carnitina se studiază oral la 2.000 mg/zi (aici 220 mg), NAC la 600-1.800 mg/zi (aici 75 mg), argininei i-au trebuit 5-9 g pentru efecte pe hormonul de creștere (aici 110 mg). Injectarea ocolește primul pasaj hepatic, dar nu compensează un factor de 10-20." },
    benefits: ["Susținere metabolică generală", "Flux sanguin (oxid nitric)", "Recuperare după efort"],
    dosing: [{ src: "Fișa furnizorului", text: "0,5-1,0 ml SC, 1-3x/săptămână, în cicluri cu pauză de eluție." }, { src: "Raport", text: "1-2 ml IM sau SC, 2-3x/săptămână, continuu." }, { src: "Planul tău", text: "1 ml = 100 U, luni/miercuri/vineri, cicluri de 8 săpt. + 2 săpt. pauză, până la epuizarea stocului." }],
    recon: { note: "Lichid gata de uz, nu se reconstituie. Răstoarnă ușor flaconul înainte de fiecare doză; cristalele fine sunt normale la această formulă, se dizolvă la omogenizare.", schemes: [{ label: "Flacon 10 ml, 86,5 mg/ml", water: 0, conc: 86.5, doses: [[43.25, "0,5 ml"], [86.5, "1,0 ml"], [129.75, "1,5 ml"]] }] },
    when: "Dimineața sau înainte de efort (fișa: „subcutanat înainte / dimineața”). Poate fi și seara, dacă ziua nu permite.",
    where: "SC: abdomen la peste 5 cm de ombilic, coapsă externă, braț extern, cu rotație. IM: coapsă (vastus lateralis), fesier ventrogluteal, deltoid doar sub 2 ml.",
    route: "SC (fișa furnizorului) sau IM (raport). Alegerea se face din aplicație.",
    storage: "Nedeschis: la întuneric, fără congelare; unele versiuni nu recomandă frigiderul (pot precipita cristale). După prima puncție: sigilat, la întuneric, 14-21 zile. Se aruncă dacă e tulbure, decolorat sau cu sediment abundent.",
    warnings: ["NAC din amestec alimentează aceeași cale ca Glutationul injectabil: sunt redundante, nu periculoase.", "Raportul îl consideră poziția cu cel mai slab raport preț/efect din comandă."],
    interactions: "Suprapunere cu Glutationul (sinteza de glutation)."
  },
  ss31: {
    what: "Tetrapeptidă sintetică (D-Arg-2,6-dimetil-Tyr-Lys-Phe-NH2), cunoscută și ca Elamipretide sau MTP-131. Singurul compus din comandă ajuns în studii clinice de fază 3 (Stealth BioTherapeutics).",
    mechanism: ["Se concentrează selectiv în membrana mitocondrială internă, unde se leagă de cardiolipină.", "Stabilizează arhitectura cristelor mitocondriale.", "Îmbunătățește cuplarea lanțului de transport de electroni și reduce scurgerea de electroni.", "Rezultat net: mai mult ATP și mai puțini radicali liberi din același substrat."],
    evidence: { level: "Studii clinice de fază 3, rezultate mixte", text: "MMPOWER-3 (miopatie mitocondrială primară) nu a atins endpoint-ul primar. TAZPOWER (sindrom Barth) parțial pozitiv. ReCLAIM și ReNEW (degenerescență maculară uscată) semnal pozitiv pe unele endpoint-uri. FDA a respins cererea pentru sindromul Barth. Cel mai riguros testat compus din comandă." },
    benefits: ["Energie celulară", "Recuperare după efort", "Protecție cardiacă și renală", "Sănătate oculară"],
    dosing: [{ src: "Fișa furnizorului", text: "5-10 mg/zi SC, dimineața; cicluri, cu interval de pauză după planul de cercetare." }, { src: "Raport", text: "În studii 40 mg/zi SC; în comunitate 5-10 mg/zi. Cure de 4-8 săptămâni." }, { src: "Planul tău", text: "5 mg = 50 U (fiolă cu 1 ml apă), zilnic, 20 zile; stocul de 10 fiole acoperă exact 20 de doze." }],
    recon: { note: "Apa bacteriostatică pe peretele fiolei, nu pe pulbere; rotește, nu agita: peptida are punți disulfidice sensibile. Limpede și incolor; tulbure, cu precipitat sau gălbui = aruncă. Ține 5-10 s înainte de a scoate acul.", schemes: [{ label: "1 ml apă (schema ta)", water: 1, conc: 10, doses: [[2.5, "25 U"], [5, "50 U"], [10, "100 U"]] }, { label: "2 ml apă (fișa: recomandată)", water: 2, conc: 5, doses: [[2.5, "50 U"], [5, "100 U"], [10, "200 U, două seringi"]] }] },
    when: "Dimineața (fișa și majoritatea protocoalelor).",
    where: "SC: abdomen, coapsă externă, braț extern, cu rotație.",
    route: "SC. Sursele nu descriu alternativă IM.",
    storage: "Pulbere: 2-8 °C pe termen scurt, -20 °C pe termen lung, ferită de lumină și umezeală. Reconstituit: 2-8 °C, 21-28 zile, fără congelare.",
    warnings: ["Un ciclu de 4-8 săptămâni ar necesita 1-3 cutii în plus față de cele 10 fiole.", "Suprapunere mitocondrială cu MOTS-c și NAD+: introduse pe rând, altfel nu poți atribui efectele."],
    interactions: "MOTS-c, NAD+ (aceeași țintă: mitocondrie și energie celulară)."
  },
  bb10: {
    what: "Blend 1:1 de BPC-157 (5 mg) și TB-500 (5 mg) în aceeași fiolă. BPC-157: peptidă de 15 aminoacizi, fragment al unei proteine protectoare din sucul gastric uman. TB-500: fragmentul sintetic al timozinei beta-4 din domeniul de legare la actină (reziduurile 17-23).",
    mechanism: ["BPC-157: puternic pro-angiogenic, crește expresia VEGFR2, activează VEGFR2-Akt-eNOS.", "BPC-157: activează FAK-paxilină în fibroblastele de tendon, accelerând migrarea celulară; crește receptorii pentru hormonul de creștere; contracarează leziunile gastrice induse de antiinflamatoare.", "TB-500: sechestrează G-actina, favorizând reorganizarea citoscheletului și migrarea celulară.", "TB-500: pro-angiogenic, reduce inflamația și fibroza, atrage celule progenitoare în țesutul lezat."],
    evidence: { level: "Preclinic (rozătoare), un singur laborator", text: "BPC-157: volum mare de studii pe șobolani, aproape toate din laboratorul Sikiric (Zagreb); niciun trial uman randomizat finalizat. TB-500: timozina beta-4 integrală testată la om cu rezultate mixte; fragmentul este studiat aproape exclusiv veterinar (interzis în cursele de cai)." },
    benefits: ["Vindecarea tendoanelor și ligamentelor", "Recuperare după accidentări", "Protecție gastrointestinală"],
    dosing: [{ src: "Raport", text: "0,5-1 mg din blend pe zi (250-500 mcg din fiecare componentă), 4-6 săptămâni. Fiind 1:1, componentele nu se pot doza separat." }, { src: "Planul tău", text: "0,5 mg = 10 U, zilnic, cicluri de 6 săpt. + 2 săpt. pauză, până la epuizarea stocului." }],
    recon: { note: "2 ml apă bacteriostatică pe perete. Dacă soluția rămâne tulbure, raportul menționează apa cu acid acetic 0,6% ca alternativă utilă mai ales pentru BPC-157. Doze mici: folosește seringă de 0,3-0,5 ml pentru precizie.", schemes: [{ label: "2 ml apă (5 mg/ml blend)", water: 2, conc: 5, doses: [[0.25, "5 U"], [0.5, "10 U"], [1, "20 U"]] }, { label: "1 ml apă (10 mg/ml)", water: 1, conc: 10, doses: [[0.25, "2,5 U"], [0.5, "5 U"], [1, "10 U"]] }] },
    when: "Dimineața; protocoalele de reparare tisulară îl folosesc la orice oră, constant.",
    where: "SC: abdomen, coapsă, braț; unele protocoale îl injectează SC cât mai aproape de zona lezată.",
    route: "SC.",
    storage: "Pulbere: 2-8 °C, ferită de lumină. Reconstituit: 2-8 °C, 21-28 zile.",
    warnings: ["Antidoping: BPC-157 (categoria S0) și TB-500 (S2) sunt interzise WADA. Risc real pentru sport federat.", "Certificatele de analiză acoperă puritatea, nu sterilitatea sau endotoxinele."],
    interactions: "Nu are suprapuneri directe în comandă."
  },
  nad: {
    what: "Nicotinamid adenin dinucleotidă, coenzimă prezentă în fiecare celulă. Nu este peptidă.",
    mechanism: ["Cofactor redox obligatoriu în glicoliză, ciclul Krebs și fosforilarea oxidativă.", "Substrat consumabil pentru sirtuine (SIRT1-7), enzimele de reglare metabolică și longevitate.", "Substrat pentru PARP, enzimele de reparare a ADN-ului.", "Precursor pentru semnalizarea prin cADPR."],
    evidence: { level: "Indirect", text: "Declinul NAD+ cu vârsta este bine documentat. Nedocumentat este că injectarea NAD+ intact l-ar corecta: molecula mare și încărcată electric nu traversează ușor membrana; extracelular este degradată de CD38 și CD73 la NMN și NR, formele care intră în celulă. Studiile umane serioase sunt pe precursori orali (NR, NMN), cu creștere a NAD+ sanguin și efecte clinice modeste." },
    benefits: ["Energie", "Claritate mentală", "Recuperare", "Efect anti-aging"],
    dosing: [{ src: "Fișa furnizorului", text: "Dimineața; start cu doză mică și creștere treptată, nu doză mare direct." }, { src: "Raport", text: "50-100 mg SC zilnic sau la 2 zile, 2-4 săptămâni. Perfuziile din clinici: 250-750 mg IV lent în 1-4 ore." }, { src: "Planul tău", text: "Titrare 25 mg (7,5 U) zile 1-3, 50 mg (15 U) zile 4-7, apoi 100 mg (30 U) zilnic; cicluri de 4 săpt. + 2 săpt. pauză." }],
    recon: { note: "Apa foarte lent pe perete; NAD+ se degradează la agitare. Limpede și incolor; galben sau tulbure = aruncă. Injectează foarte lent: administrat repede dă arsură locală intensă, valuri de căldură, greață și senzație de presiune toracică. Este exact motivul pentru care clinicile perfuzează lent.", schemes: [{ label: "3 ml apă (333 mg/ml, schema ta)", water: 3, conc: 333.33, doses: [[25, "7,5 U"], [50, "15 U"], [75, "22,5 U"], [100, "30 U"]] }, { label: "10 ml apă (100 mg/ml)", water: 10, conc: 100, doses: [[50, "50 U"], [100, "100 U"]] }] },
    when: "Dimineața (fișa și raportul). Seara poate da agitație.",
    where: "SC: abdomen, coapsă, braț; rotează, locul poate rămâne sensibil.",
    route: "SC lent. IV doar în clinică.",
    storage: "Pulbere: 2-8 °C scurt, -20 °C lung, ferită de lumină și umezeală. Reconstituit: 2-8 °C, ideal 14 zile, maxim 21; congelarea distruge molecula.",
    warnings: ["Cea mai dureroasă injecție din comandă. Nu crește doza dacă reacția locală e intensă.", "Suprapunere mitocondrială cu SS-31 și MOTS-c."],
    interactions: "SS-31, MOTS-c."
  },
  gsh: {
    what: "Tripeptidă gamma-Glu-Cys-Gly, principalul antioxidant intracelular al organismului.",
    mechanism: ["Donor de electroni pentru glutation-peroxidaze, care neutralizează peroxizii.", "Substrat pentru glutation-S-transferaze în detoxifierea hepatică de fază II.", "Menține raportul redox celular.", "Regenerează formele active ale vitaminelor C și E."],
    evidence: { level: "Studii clinice umane (IV), avertizări de reglementare", text: "Biologia este incontestabilă; suplimentarea injectabilă este alt subiect. Oral are biodisponibilitate slabă. IV a fost studiat în Parkinson (rezultate mixte, tranzitorii), ficat gras și chimioterapie. Cea mai răspândită utilizare globală este depigmentarea pielii, în Asia de Sud-Est." },
    benefits: ["Antioxidant sistemic", "Susținerea detoxifierii hepatice", "Luminozitatea pielii"],
    dosing: [{ src: "Fișa furnizorului", text: "100-200 mg SC, 2-3x/săptămână, dimineața sau seara; cicluri cu pauză." }, { src: "Raport", text: "600-1.200 mg IM sau IV lent, 1-3x/săptămână, 4-8 săptămâni." }, { src: "Planul tău", text: "SC: 200 mg = 100 U, luni/miercuri/vineri, cicluri de 8 săpt. + 2. IM (opțional): 600 mg = 3 ml, luni și joi, 10 doze." }],
    recon: { note: "Se oxidează în contact cu aerul: apa pe perete, cât mai puțin contact cu aerul, fără agitare. Incolor; galben = oxidat, se aruncă. Soluția este acidă, usturimea la SC este obișnuită. Nu prepara prea diluat.", schemes: [{ label: "3 ml apă (200 mg/ml, schema ta)", water: 3, conc: 200, doses: [[100, "50 U"], [200, "100 U"], [300, "150 U"], [600, "300 U = 3 ml, IM"]] }, { label: "2 ml apă (300 mg/ml)", water: 2, conc: 300, doses: [[100, "33 U"], [200, "67 U"], [300, "100 U"]] }] },
    when: "Dimineața sau seara (fișa); planul tău: seara.",
    where: "SC: abdomen, coapsă, braț. IM: coapsă sau fesier ventrogluteal (3 ml nu încape în deltoid).",
    route: "SC (fișa) sau IM (raport). Alegerea se face din aplicație.",
    storage: "Pulbere: 2-8 °C, ferită de lumină. Reconstituit: 7-14 zile, nu mai mult; fiolă nouă în fiecare luni.",
    warnings: ["Autoritățile din Filipine și SUA au emis avertizări pentru glutationul IV de albire: sindrom Stevens-Johnson, necroliză epidermică toxică, insuficiență renală, embolie gazoasă, infecții din preparate nesterile. Riscul vine din calea de administrare și calitatea preparatului.", "Redundant cu NAC din SHB."],
    interactions: "SHB (NAC este precursor de glutation)."
  },
  motsc: {
    what: "Peptidă de 16 aminoacizi codificată în ADN-ul mitocondrial (gena 12S rRNA), una dintre peptidele derivate mitocondrial. Descrisă de Lee și Cohen (USC), Cell Metabolism 2015.",
    mechanism: ["Activează AMPK, senzorul energetic central al celulei.", "Inhibă calea folat-ciclul metioninei, acumulează AICAR, care activează AMPK.", "Sub stres metabolic translocă în nucleu și reglează gene adaptive prin ATF1.", "Ameliorează sensibilitatea la insulină și captarea glucozei în mușchiul scheletic."],
    evidence: { level: "Preclinic solid", text: "Cele mai bune date preclinice din grupul de longevitate: la șoareci previne rezistența la insulină indusă de dietă și obezitatea legată de vârstă. La om nivelurile scad cu vârsta și cresc după efort; un polimorfism (m.1382A>C) e asociat cu longevitatea la bărbații japonezi. Niciun trial clinic de intervenție finalizat." },
    benefits: ["Sensibilitate la insulină", "Capacitate de efort", "Compoziție corporală"],
    dosing: [{ src: "Fișa furnizorului", text: "2,5-10 mg SC, 1-3x/săptămână, dimineața; cicluri cu pauză." }, { src: "Raport", text: "5-10 mg/săptămână, fracționat în 2-3 administrări SC, 4-8 săptămâni." }, { src: "Planul tău", text: "5 mg = 100 U, luni și joi (10 mg/săpt.), cicluri de 8 săpt. + 2 săpt. pauză." }],
    recon: { note: "Stabilitate mai slabă decât majoritatea peptidelor: apa bacteriostatică obligatoriu, 1-2 minute până se dizolvă, fără agitare. Folosește în 7-14 zile.", schemes: [{ label: "2 ml apă (5 mg/ml, schema ta)", water: 2, conc: 5, doses: [[2.5, "50 U"], [5, "100 U"], [10, "200 U, două seringi"]] }, { label: "1 ml apă (10 mg/ml)", water: 1, conc: 10, doses: [[2.5, "25 U"], [5, "50 U"], [10, "100 U"]] }] },
    when: "Dimineața, în acord cu activarea metabolică (fișa). Unii îl iau înainte de antrenament.",
    where: "SC: abdomen, coapsă, braț.",
    route: "SC.",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 7-14 zile (maxim 21-28).",
    warnings: ["Efect real pe glicemie în modele animale: cu antidiabetice sau episoade de hipoglicemie, monitorizează.", "Suprapunere mitocondrială cu SS-31 și NAD+."],
    interactions: "SS-31, NAD+, medicație antidiabetică."
  },
  ghk: {
    what: "Tripeptidă Gly-His-Lys complexată cu cupru bivalent, prezentă natural în plasmă: aproximativ 200 ng/ml la 20 de ani, 80 ng/ml la 60 de ani.",
    mechanism: ["Modulează expresia a aproximativ 4.000 de gene, majoritatea spre un profil tânăr.", "Stimulează sinteza de colagen tip I, elastină, glicozaminoglicani și decorină.", "Pro-angiogenic (VEGF, FGF-2); atrage celule imune și celule stem în plagă.", "Antioxidant și antiinflamator; reduce TGF-beta1, ceea ce influențează cicatrizarea.", "Cuprul este cofactor pentru lizil-oxidază, enzima care reticulează colagenul și elastina."],
    evidence: { level: "Clinic pentru aplicare topică; sistemic slab", text: "Studii clinice pe riduri, fermitate și vindecarea plăgilor la aplicare pe piele. Pentru injectare sistemică, dovezile sunt extrapolate din datele topice și in vitro." },
    benefits: ["Piele", "Păr", "Vindecarea țesuturilor", "Aspectul cicatricilor"],
    dosing: [{ src: "Fișa furnizorului", text: "2,5-10 mg SC, dimineața sau seara; cicluri cu pauză de eluție." }, { src: "Raport", text: "Topic 1-3 mg/ml în ser, zilnic. Injectabil SC sau intradermic 1-2 mg. Fiola de 50 mg este dimensionată pentru uz topic sau microneedling." }, { src: "Planul tău", text: "2,5 mg = 25 U, zilnic, seara, cicluri de 8 săpt. + 4 săpt. pauză, cu analize cupru/zinc la fiecare sfârșit de ciclu." }],
    recon: { note: "Soluția albastru-deschis este normală, nu semn de degradare. Tulbure sau cu precipitat = aruncă. Ține 5-10 s înainte de a scoate acul.", schemes: [{ label: "5 ml apă (10 mg/ml, schema ta)", water: 5, conc: 10, doses: [[1, "10 U"], [2, "20 U"], [2.5, "25 U"], [5, "50 U"], [10, "100 U"]] }, { label: "2 ml apă (25 mg/ml)", water: 2, conc: 25, doses: [[2.5, "10 U"], [5, "20 U"], [10, "40 U"], [25, "100 U"]] }] },
    when: "Dimineața sau seara (fișa); planul tău: seara.",
    where: "SC: abdomen, coapsă, braț, cu rotație. Topic: aplicat pe piele; intradermic în cabinet.",
    route: "SC (fișa), intradermic sau topic (raport).",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 21-28 zile.",
    warnings: ["Încărcare cu cupru: 50 mg GHK-Cu conțin 8-9 mg cupru elementar; doza zilnică recomandată de cupru e 0,9 mg, limita superioară tolerabilă 10 mg/zi. Injectat, cuprul ocolește reglarea absorbției intestinale. La 2,5 mg/zi ≈ 0,4 mg cupru/zi; pe 188 de doze ≈ 80 mg. Excesul produce stres oxidativ, scade zincul, afectează ficatul.", "Analize cupru și zinc seric înainte și la fiecare sfârșit de ciclu; nu începe ciclul următor dacă au crescut."],
    interactions: "Zinc (cuprul în exces îl scade)."
  },
  epi: {
    what: "Tetrapeptidă sintetică Ala-Glu-Asp-Gly (Epitalon, AEDG), creată de Vladimir Khavinson la Institutul de Bioreglare și Gerontologie din Sankt Petersburg, ca analog al epitalaminei, extract de glandă pineală bovină.",
    mechanism: ["Activarea telomerazei prin creșterea expresiei hTERT, demonstrată in vitro pe fibroblaste umane.", "Normalizarea secreției de melatonină și a ritmului circadian prin acțiune pineală.", "Legare la secvențe specifice de ADN (modelul Khavinson de bioreglare epigenetică), mecanism ipotetic, netestat independent."],
    evidence: { level: "Preclinic slab", text: "Aproape toate studiile provin dintr-un singur grup, publicate în reviste rusești, cu metodologie care nu ar trece azi un peer-review occidental. Extinderea duratei de viață e pe șoareci și șobolani. Niciun studiu randomizat placebo pe oameni. Replicare independentă a activării telomerazei: limitată." },
    benefits: ["Somn și ritm circadian", "Funcție imună", "Efect general anti-aging"],
    dosing: [{ src: "Fișa furnizorului", text: "5-10 mg SC, seara, în acord cu ritmul pineal; cicluri, nu continuu." }, { src: "Raport", text: "5-10 mg/zi SC, cure de 10-20 zile, repetate de 1-2 ori pe an." }, { src: "Planul tău", text: "5 mg = 100 U, zilnic, seara, 20 zile (stocul); repetare peste 6 luni." }],
    recon: { note: "Apa pe perete, rotire ușoară, fără agitare. Limpede și incolor.", schemes: [{ label: "2 ml apă (5 mg/ml, schema ta)", water: 2, conc: 5, doses: [[5, "100 U"], [10, "200 U, două seringi"]] }, { label: "1 ml apă (10 mg/ml)", water: 1, conc: 10, doses: [[5, "50 U"], [10, "100 U"]] }] },
    when: "Seara, înainte de culcare (fișa: ritmul fiziologic al glandei pineale).",
    where: "SC: abdomen, coapsă, braț.",
    route: "SC.",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung, ferită de lumină. Reconstituit: 2-8 °C, 21-30 zile.",
    warnings: ["Activarea telomerazei este mecanismul prin care majoritatea celulelor tumorale devin nemuritoare. Fără date de siguranță pe termen lung la om. De evitat la antecedente oncologice personale sau familiale.", "Aceeași familie cu Pinealon; raportul recomandă să nu fie testate simultan."],
    interactions: "Pinealon (aceeași familie Khavinson)."
  },
  pin: {
    what: "Tripeptidă Glu-Asp-Arg (EDR), tot din seria Khavinson, promovată ca bioregulator pentru creier.",
    mechanism: ["Penetrare nucleară și modulare a expresiei genice în neuroni (propus).", "Protecție împotriva hipoxiei și a stresului oxidativ.", "Efect asupra sintezei proteice neuronale."],
    evidence: { level: "Practic absente", text: "Cele mai slabe dovezi din comandă: date exclusiv preclinice rusești, in vitro și pe rozătoare. Fără date umane în literatura internațională indexată. Mecanismul central nu a fost validat independent. Raportul îl vede drept primul candidat de scos pe criteriul dovezi/cost." },
    benefits: ["Memorie", "Concentrare", "Neuroprotecție", "Recuperare după stres"],
    dosing: [{ src: "Fișa furnizorului", text: "1-10 mg SC, înainte de culcare; ciclu de 10-20 zile, apoi pauză." }, { src: "Raport", text: "5-10 mg/zi SC, 10-20 zile." }, { src: "Planul tău", text: "5 mg = 100 U, zilnic, seara, 20 zile (stocul), în paralel cu Epithalon la alegerea ta." }],
    recon: { note: "Apa pe perete, rotire ușoară. Limpede și incolor; tulbure = aruncă.", schemes: [{ label: "2 ml apă (5 mg/ml, schema ta)", water: 2, conc: 5, doses: [[1, "20 U"], [2, "40 U"], [5, "100 U"], [10, "200 U, două seringi"]] }, { label: "1 ml apă (10 mg/ml)", water: 1, conc: 10, doses: [[1, "10 U"], [2, "20 U"], [5, "50 U"], [10, "100 U"]] }] },
    when: "Seara, înainte de culcare (fișa).",
    where: "SC: abdomen, coapsă, braț.",
    route: "SC.",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 21-28 zile.",
    warnings: ["Suprapunere cu Epithalon (aceeași familie, aceeași bază de dovezi slabă): un efect apărut în perioada comună nu poate fi atribuit."],
    interactions: "Epithalon."
  },
  dsip: {
    what: "Nonapeptidă Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu (Delta Sleep-Inducing Peptide), izolată în 1974 din sângele venos cerebral al iepurilor în somn indus electric.",
    mechanism: ["Mecanism neclar după 50 de ani; nu are receptor propriu identificat.", "Se propune modularea somnului cu unde delta.", "Influențarea axei hipotalamo-hipofizare: GHRH, ACTH, somatostatină.", "Efecte asupra percepției durerii și a răspunsului la stres."],
    evidence: { level: "Vechi și inconsistent", text: "Studiile umane din anii 1970-80 au dat rezultate contradictorii: unele arată reducerea latenței de adormire, altele niciun efect. Date ceva mai interesante pe sevrajul la opiacee și durerea cronică, pe loturi mici, nereplicate." },
    benefits: ["Somn profund", "Reducerea anxietății", "Recuperare"],
    dosing: [{ src: "Fișa furnizorului", text: "100-500 mcg SC, cu 30-60 min înainte de culcare; cicluri de 4-8 săptămâni, apoi pauză." }, { src: "Raport", text: "100-300 mcg SC, seara, intermitent, la nevoie." }, { src: "Planul tău", text: "200 mcg = 8 U, zilnic, seara, cicluri de 4 săpt. + 2 săpt. pauză." }],
    recon: { note: "ATENȚIE LA UNITĂȚI: fiola are 5 mg = 5.000 mcg, adică 17-50 de doze. O seringă plină (100 U) la 2 ml apă înseamnă 2,5 mg, de 12 ori doza. Doza corectă e 8 U, o zecime de seringă. Seringă de 0,3 ml.", schemes: [{ label: "2 ml apă (2,5 mg/ml, schema ta)", water: 2, conc: 2.5, doses: [[0.1, "4 U"], [0.2, "8 U"], [0.25, "10 U"], [0.5, "20 U"]] }, { label: "5 ml apă (1 mg/ml)", water: 5, conc: 1, doses: [[0.1, "10 U"], [0.2, "20 U"], [0.25, "25 U"], [0.5, "50 U"]] }] },
    when: "Seara, cu 30-60 de minute înainte de culcare.",
    where: "SC: abdomen, coapsă, braț.",
    route: "SC.",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 21-28 zile.",
    warnings: ["Singura substanță din comandă unde o eroare de reconstituire înseamnă supradoză de zece ori. Se dozează în micrograme."],
    interactions: "Selank (ambele acționează pe anxietate și somn, dar prin căi diferite)."
  },
  semax: {
    what: "Heptapeptidă sintetică: fragmentul ACTH(4-7) Met-Glu-His-Phe legat de Pro-Gly-Pro. Derivat de ACTH fără activitate hormonală corticotropă. Medicament înregistrat în Rusia pentru accident vascular cerebral și neuropatie optică.",
    mechanism: ["Crește expresia BDNF și NGF în hipocamp și cortex.", "Modulează sistemele dopaminergic și serotoninergic.", "Neuroprotector în ischemie: reduce zona de infarct în modele animale.", "Inhibă enkefalinazele, la fel ca Selank."],
    evidence: { level: "Clinic doar în Rusia", text: "Studiile clinice rusești în AVC ischemic acut raportează ameliorare neurologică; folosit în protocoale spitalicești acolo. Replicare occidentală independentă: absentă. Datele preclinice de neuroprotecție sunt consistente și vin din mai multe laboratoare." },
    benefits: ["Funcție cognitivă", "Atenție", "Neuroprotecție", "Recuperare după efort mental"],
    dosing: [{ src: "Fișa furnizorului", text: "200-500 mcg SC, dimineața sau până după-amiază; evită seara, dă insomnie. Cicluri de 4-6 săptămâni, apoi pauză." }, { src: "Raport", text: "300-600 mcg/zi intranazal pentru uz cognitiv; în spital, pentru AVC, până la 12 mg/zi. Formularea studiată clinic este intranazală 0,1% sau 1%." }, { src: "Planul tău", text: "300 mcg = 12 U, zilnic, dimineața, SC, cicluri de 6 săpt. + 2 săpt. pauză." }],
    recon: { note: "Micrograme: 12 U, nu seringă plină. Seringă de 0,3 ml. Soluția reconstituită poate fi folosită și intranazal cu un flacon cu pipetă, formularea studiată clinic, dar nu e cea din plan.", schemes: [{ label: "2 ml apă (2,5 mg/ml, schema ta)", water: 2, conc: 2.5, doses: [[0.2, "8 U"], [0.3, "12 U"], [0.5, "20 U"]] }, { label: "5 ml apă (1 mg/ml)", water: 5, conc: 1, doses: [[0.2, "20 U"], [0.3, "30 U"], [0.5, "50 U"]] }] },
    when: "Dimineața până după-amiază. Nu seara.",
    where: "SC: abdomen, coapsă, braț. Intranazal: picături în fiecare nară.",
    route: "SC (fișa) sau intranazal (raport, calea validată clinic).",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 21-28 zile.",
    warnings: ["Fiolele injectabile presupun o cale diferită de cea validată clinic (intranazal).", "Împreună cu Selank inhibă aceleași enzime; în Rusia se dau des împreună, dar pentru evaluare individuală se introduc separat."],
    interactions: "Selank (sistem enkefalinergic)."
  },
  selank: {
    what: "Heptapeptidă sintetică: fragmentul tuftsin Thr-Lys-Pro-Arg legat de stabilizatorul Pro-Gly-Pro. Dezvoltată la Institutul de Genetică Moleculară din Moscova, înregistrată ca medicament în Rusia.",
    mechanism: ["Modulează sistemul GABA-ergic, cu afinitate pentru situsuri GABA-A.", "Crește expresia BDNF în hipocamp.", "Inhibă enkefalinazele, prelungind acțiunea enkefalinelor endogene.", "Componenta tuftsin are efect imunomodulator."],
    evidence: { level: "Clinic doar în Rusia", text: "Studii rusești în tulburarea de anxietate generalizată raportează eficacitate comparabilă cu benzodiazepinele, fără sedare, toleranță sau sindrom de întrerupere. Ar fi remarcabil dacă ar fi replicat independent; nu a fost." },
    benefits: ["Anxietate", "Rezistență la stres", "Claritate mentală fără sedare"],
    dosing: [{ src: "Fișa furnizorului", text: "250-500 mcg SC, dimineața sau seara; cicluri de 4-6 săptămâni, apoi pauză." }, { src: "Raport", text: "250-500 mcg de 1-3 ori pe zi, intranazal, cure de 10-14 zile. Formularea studiată clinic este intranazală." }, { src: "Planul tău", text: "300 mcg = 12 U, zilnic, seara, SC, cicluri de 6 săpt. + 2 săpt. pauză." }],
    recon: { note: "Micrograme: 12 U, nu seringă plină. Seringă de 0,3 ml. Poate fi folosit și intranazal din soluția reconstituită.", schemes: [{ label: "2 ml apă (2,5 mg/ml, schema ta)", water: 2, conc: 2.5, doses: [[0.25, "10 U"], [0.3, "12 U"], [0.5, "20 U"]] }, { label: "5 ml apă (1 mg/ml)", water: 5, conc: 1, doses: [[0.25, "25 U"], [0.3, "30 U"], [0.5, "50 U"]] }] },
    when: "Dimineața sau seara (fișa); planul tău: seara, separat de Semax dimineața.",
    where: "SC: abdomen, coapsă, braț. Intranazal: picături în fiecare nară.",
    route: "SC (fișa) sau intranazal (raport, calea validată clinic).",
    storage: "Pulbere: 2-8 °C, -20 °C pe termen lung. Reconstituit: 2-8 °C, 21-30 zile.",
    warnings: ["Fiolele injectabile presupun o cale diferită de cea validată clinic.", "Suprapunere cu Semax (enkefalinaze)."],
    interactions: "Semax."
  }
};

const INFO_GENERAL = {
  disclaimer: "Sinteză informativă din fișa furnizorului MKM și din raportul de analiză (19 august 2026), nu recomandare medicală. Niciuna dintre substanțe nu este autorizată ca medicament în România sau UE. Dozele sunt cele raportate în literatură și comunitate, nevalidate clinic. Discută cu un medic, mai ales dacă iei alte medicamente, ai o afecțiune cronică sau antecedente oncologice.",
  formula: "Unități de tras = (doza dorită în mg ÷ mg totale din fiolă) × ml apă adăugați × 100. Seringa U-100: 1 ml = 100 U.",
  general: [
    "O singură substanță nouă la un moment dat, cu cel puțin două săptămâni între introduceri, altfel nu poți atribui efectele.",
    "Prima administrare la o fracțiune din doză, ca test de tolerabilitate, și nu seara târziu.",
    "Jurnal: data, substanța, doza, locul injecției, ce ai simțit în primele 24 de ore.",
    "Analize de referință înainte de start și la 8-12 săptămâni: hemoleucogramă, glicemie, HbA1c, transaminaze, creatinină, lipide; cupru și zinc pentru GHK-Cu.",
    "Oprire imediată și consult medical la: febră sau frison după injecție, roșeață care se extinde, dificultate de respirație, umflarea feței sau gâtului, durere toracică.",
    "Certificatele de analiză din dosar acoperă puritatea (HPLC) și identitatea, nu sterilitatea sau endotoxinele. Pentru un injectabil, exact acestea contează pentru siguranța acută: endotoxina dă febră și frisoane, pulberea nesterilă dă abces sau infecție."
  ],
  water: "Apa bacteriostatică conține 0,9% alcool benzilic, permite puncții multiple ale aceleiași fiole și se folosește 28 de zile de la prima puncție, la frigider. Apa sterilă simplă nu are conservant: soluția ține 24 de ore. Apa cu acid acetic 0,6% e pentru peptidele care nu se dizolvă în apă neutră, în practică mai ales BPC-157."
};
